version: 0.2

# run-as: Linux-user-name

env:
#  shell: shell-tag
#  variables:
#    key: "value"
  parameter-store:
    ACCOUNT_ID: "ACCOUNT_ID"
    ECR_WEB_NAME: "ECR_WEB_NAME"
#  exported-variables:
#    - variable
#    - variable
  secrets-manager:
    DOCKERHUB_USER: "prod/dockerhub:DOCKERHUB_USER"
    DOCKERHUB_PASS: "prod/dockerhub:DOCKERHUB_PASS"
#  git-credential-helper: no | yes
#
#proxy:
#  upload-artifacts: no | yes
#  logs: no | yes

#batch:
#  fast-fail: false | true
#    # build-list:
#    # build-matrix:
#    # build-graph:

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
  build:
    on-failure: ABORT
    commands:
      - echo Start Build...
      - docker build -t study-vue3-web -f ./docker/web/Dockerfile .
  post_build:
    on-failure: ABORT
    commands:
      - echo Start Post Build...
      - docker tag study-vue3-web ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/${ECR_WEB_NAME}:latest
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/${ECR_WEB_NAME}:latest
#reports:
#  report-group-name-or-arn:
#    files:
#      - location
#      - location
#    base-directory: location
#    discard-paths: no | yes
#    file-format: report-format
#artifacts:
#  files:
#    - location
#    - location
#  name: artifact-name
#  discard-paths: no | yes
#  base-directory: location
#  exclude-paths: excluded paths
#  enable-symlinks: no | yes
#  s3-prefix: prefix
#  secondary-artifacts:
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      name: secondary-artifact-name
#      discard-paths: no | yes
#      base-directory: location
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: no | yes
#      base-directory: location
#cache:
#  paths:
#    - path
#    - path
