version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:8000"
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:80"
